### ISSUE TITLE
**Appointment Table Click Event**

### ISSUE THREAD

**Issue by GISJohnECS** [bec-gis-department/staking-appointments#28]
Develop method that allows the user to click on a *CELL* in the Appointment *Data Table*. Ideally We want this to filter/ highlight that point on the map, however we can just focus on printing the output Job Number from the cell.

- [x] Setup Click Event for Data Table
- [x] Event must execute a print statement that outputs the Jobnumber of the cell clicked
- [x] Set this event to filter the map (This was working but with script adjustments I broke it.. my b)

https://stackoverflow.com/questions/36132730/determine-if-dt-datatable-is-clicked-in-shiny-app

**Comment by GISJohnECS** [comment]
`  #-----------------------------------------------------------------------------
  #Here is where the data table is started
  output$apttable = DT::renderDataTable({
    datatable(at, rownames = TRUE, selection = list(mode= "single",target="cell"))
  })
  
  # Here is where we are filtering the map by the click event
  observe({
    selected_apt <- input$apttable_cell_clicked 
    # Just for the Memes we are printing the Job Number of the Cell we are Selecting
    print(selected_apt$value)
  
    # This should be filtering the map, but it isn't...
    filteredselected_apts <- data %>% filter(data$jobnumber %in% selected_apt$value)
  
    #Here is our leaflet Proxy that sets the map visual (May be a good idea to functionalize this somehow because we re-use it per map filter -\_(",)_/-)
    leafletProxy("map") %>% clearMarkers() %>% 
    addCircleMarkers(lng = filteredselected_apts$Longitude,
                       lat = filteredselected_apts$Latitude,
                       fillColor =  "blue",
                       color = "black",
                       radius = 14, 
                       stroke = TRUE,
                       weight = 2,
                       fillOpacity = 0.7,
                       #added in pathOptions
                       options = pathOptions(pane = "tblapts"),
                       popup = paste("<h2>", df$jobnumber,"</h2>", "<br>",   
                                     "<b>Job Name:</b>", df$jobname, "<br>",   
                                     "<b>Pole Number:</b>",df$polenumber, "<br>",    
                                     "<b>Address:</b>", df$houseno," ",df$address," ", "<br>",   
                                     "<b>Meeting Location:</b>", df$meetinglocation, "<br>",   
                                     "<b>Appointment Time:</b>",df$appointmenttime, "<br>",   
                                     "<b>Staker:</b>", df$staker, "<br>",   
                                     "<b>Appointmet Date:</b>",df$appointmentdate, "<br>"))
   })`

**Comment by GISJohnECS** [comment]
Don't close issues before they are reviewed by an admin @BKM24

**Comment by BKM24** [comment]
my bad!!

**Comment by GISJohnECS** [comment]
Though I am sure everything is working, if it was a big software project and this issue was closed before an admin reviewed it and lets say some small trace of this issue remained, I may miss this ticket and then a duplicate issue gets opened up.

**Comment by BKM24** [comment]
Yes sir! I understand, that's my bad
