### ISSUE TITLE
Map Circle Markers not displaying when app is run

### ISSUE THREAD

**Issue by BKM24** [bec-gis-department/staking-appointments#38]
When i tried load the data frame "staking_data" back into the code it was giving me the error message "Warning: Error in validateCoords: addCircleMarkers requires non-NULL longitude/latitude values", i retyped in the text "lng = filtered_apts$longitude,
                       lat = filtered_apts$latitude," because in the past that refreshed the app and it worked the next time i ran it, now the app loads no points at all.

**Comment by GISJohnECS** [comment]
Issue was with defining sorted_Apps variable
`saveRDS(sorted_Apps, "C:/Dev/Staking Isochrone/staking-appointments/stakingApp/apt_table.rds")`

Variable sorted_Apps should have been sortedApps as this is what we are storing our variable to:
```
#DCAST Data to Data Table Format
sortedApps <- dcast(p, staker ~ appointmenttime, fun.aggregate = min, drop=FALSE, fill=NULL)
```
